import "dotenv/config";
import mongoose from "mongoose";
import { Category } from "../models/Category.js";
import { Product } from "../models/Product.js";

const categoriesData = [
  {
    name: "Electronics",
    description: "Cutting-edge gadgets, computing gear, audio equipment, and smart devices.",
  },
  {
    name: "Fashion",
    description: "Contemporary apparel, timeless essentials, premium outerwear, and knitwear.",
  },
  {
    name: "Footwear",
    description: "Engineered sneakers, leather boots, loafers, and high-performance trail shoes.",
  },
  {
    name: "Accessories",
    description: "Precision chronographs, handcrafted leather goods, sunglasses, and bags.",
  },
  {
    name: "Home & Living",
    description: "Modern minimalist home decor, ergonomic work gear, and ambient lighting.",
  },
  {
    name: "Audio & Sound",
    description: "High-fidelity headphones, studio audio monitors, and wireless sound systems.",
  },
  {
    name: "Bags & Travel",
    description: "Weatherproof commuter backpacks, leather duffles, and tech sling bags.",
  },
];

// 105 Curated High-Quality Products (15 Products per Category, All Price Tiers)
const productsData = [
  // =========================================================================
  // 1. ELECTRONICS (15 Products: <1k, 1k-3k, 3k-8k, >8k)
  // =========================================================================
  {
    title: "Braided 100W Fast-Charging USB-C Cable",
    category: "Electronics",
    brand: "Signal Works",
    description: "Heavy-duty nylon braided 2-meter USB-C to USB-C cable supporting 100W Power Delivery (PD) and 480Mbps data transfer speeds with reinforced strain relief.",
    basePrice: 999,
    baseDiscountPrice: 699,
    stock: 80,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=900&q=80", publicId: "prod/cable-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 340,
    tags: ["electronics", "cable", "charger", "deals"],
    featured: false,
  },
  {
    title: "Ultra-Slim 4-Port USB 3.0 Data Hub",
    category: "Electronics",
    brand: "Signal Works",
    description: "Compact aluminum 4-port USB 3.0 splitter offering 5Gbps high-speed data sync, individual LED indicators, and plug-and-play driverless compatibility.",
    basePrice: 999,
    baseDiscountPrice: 799,
    stock: 65,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=900&q=80", publicId: "prod/usbhub-1", isPrimary: true }],
    ratingsAverage: 4.6,
    ratingsQuantity: 190,
    tags: ["electronics", "hub", "accessories", "sale"],
    featured: false,
  },
  {
    title: "PocketPower 65W GaN Travel Charger",
    category: "Electronics",
    brand: "Signal Works",
    description: "Compact Gallium Nitride (GaN) fast charger with foldable prongs and dual USB-C + USB-A ports capable of powering laptops and smartphones simultaneously.",
    basePrice: 2499,
    baseDiscountPrice: 1899,
    stock: 62,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=900&q=80", publicId: "prod/gan-1", isPrimary: true }],
    ratingsAverage: 4.9,
    ratingsQuantity: 440,
    tags: ["electronics", "charger", "travel", "bestseller"],
    featured: false,
  },
  {
    title: "Lumina Smart Desk Ambient Lightbar",
    category: "Electronics",
    brand: "Nova Tech",
    description: "Monitor-mounted asymmetric optical lightbar that illuminates your workstation without screen glare, with wireless rotary dial control and auto-dimming sensor.",
    basePrice: 3499,
    baseDiscountPrice: 2699,
    stock: 40,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80", publicId: "prod/lightbar-1", isPrimary: true }],
    ratingsAverage: 4.6,
    ratingsQuantity: 310,
    tags: ["electronics", "desk", "lighting", "bestseller"],
    featured: false,
  },
  {
    title: "Vortex Gaming Ergonomic Mouse",
    category: "Electronics",
    brand: "Signal Works",
    description: "Ultralightweight 58g honey-comb design with PAW3395 26K DPI optical sensor, pure PTFE glides, and lag-free 2.4GHz wireless connection.",
    basePrice: 3999,
    baseDiscountPrice: 2999,
    stock: 45,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=900&q=80", publicId: "prod/mouse-1", isPrimary: true }],
    ratingsAverage: 4.5,
    ratingsQuantity: 178,
    tags: ["electronics", "gaming", "mouse", "sale"],
    featured: false,
  },
  {
    title: "Apex Magnetic Wireless Power Hub",
    category: "Electronics",
    brand: "Signal Works",
    description: "3-in-1 fast-charging stand for iPhone, Apple Watch, and AirPods with aerospace-grade aluminum alloy build and intelligent temperature regulation.",
    basePrice: 4299,
    baseDiscountPrice: 3499,
    stock: 55,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=900&q=80", publicId: "prod/charger-1", isPrimary: true }],
    ratingsAverage: 4.6,
    ratingsQuantity: 215,
    tags: ["electronics", "charger", "wireless", "sale"],
    featured: false,
  },
  {
    title: "Eon Mini Smart Home Hub",
    category: "Electronics",
    brand: "Nova Tech",
    description: "Universal smart home bridge supporting Matter, Zigbee, and Thread protocols with voice assistant integration and automated scene controllers.",
    basePrice: 4999,
    baseDiscountPrice: 3899,
    stock: 33,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=900&q=80", publicId: "prod/hub-1", isPrimary: true }],
    ratingsAverage: 4.4,
    ratingsQuantity: 82,
    tags: ["electronics", "smarthome", "iot"],
    featured: false,
  },
  {
    title: "StreamCast Studio USB Microphone",
    category: "Electronics",
    brand: "Aether Audio",
    description: "Broadcast-quality cardioid condenser microphone with built-in pop filter, zero-latency headphone monitor jack, and tap-to-mute touch sensor.",
    basePrice: 6299,
    baseDiscountPrice: 4999,
    stock: 28,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=900&q=80", publicId: "prod/mic-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 120,
    tags: ["electronics", "audio", "microphone", "deals"],
    featured: false,
  },
  {
    title: "CyberGrip Wireless Pro Controller",
    category: "Electronics",
    brand: "Signal Works",
    description: "Multi-platform wireless gamepad with Hall Effect anti-drift magnetic joysticks, mechanical micro-switch buttons, and customizable rear trigger paddles.",
    basePrice: 5999,
    baseDiscountPrice: 4499,
    stock: 32,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?auto=format&fit=crop&w=900&q=80", publicId: "prod/controller-1", isPrimary: true }],
    ratingsAverage: 4.7,
    ratingsQuantity: 210,
    tags: ["electronics", "gaming", "controller", "bestseller"],
    featured: true,
  },
  {
    title: "Quantum Pro Mechanical Keyboard",
    category: "Electronics",
    brand: "Signal Works",
    description: "Engineered with hot-swappable Gateron mechanical switches, sound-dampening gasket mount, and per-key customizable RGB lighting.",
    basePrice: 7499,
    baseDiscountPrice: 5999,
    stock: 35,
    hasVariants: true,
    variants: [
      {
        sku: "QPRO-KB-RED",
        attributes: { color: "Midnight Black", size: "75%", material: "Aluminum Chassis" },
        price: 7499,
        discountPrice: 5999,
        stock: 18,
        image: { url: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80", publicId: "prod/kb-red" },
      },
      {
        sku: "QPRO-KB-BRN",
        attributes: { color: "Chalk White", size: "75%", material: "Aluminum Chassis" },
        price: 7499,
        discountPrice: 5999,
        stock: 17,
        image: { url: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=900&q=80", publicId: "prod/kb-brn" },
      },
    ],
    images: [
      { url: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80", publicId: "prod/kb-1", isPrimary: true },
      { url: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=900&q=80", publicId: "prod/kb-2", isPrimary: false },
    ],
    ratingsAverage: 4.8,
    ratingsQuantity: 142,
    tags: ["electronics", "gaming", "keyboard", "deals", "bestseller"],
    featured: true,
  },
  {
    title: "HyperSync 10-in-1 Thunderbolt 4 Dock",
    category: "Electronics",
    brand: "Signal Works",
    description: "Universal docking station supporting dual 4K@60Hz displays, 100W PD host charging, Gigabit Ethernet, SD/TF readers, and high-speed 10Gbps USB-C ports.",
    basePrice: 11999,
    baseDiscountPrice: 9499,
    stock: 19,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=900&q=80", publicId: "prod/dock-1", isPrimary: true }],
    ratingsAverage: 4.7,
    ratingsQuantity: 64,
    tags: ["electronics", "dock", "accessories", "deals"],
    featured: false,
  },
  {
    title: "VisionUltra 4K USB-C Designer Monitor",
    category: "Electronics",
    brand: "Nova Tech",
    description: "27-inch IPS UHD display with 99% sRGB color gamut coverage, HDR400 certified brightness, 90W single-cable USB-C power delivery, and ultra-thin borderless bezel.",
    basePrice: 28999,
    baseDiscountPrice: 24999,
    stock: 20,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=80", publicId: "prod/monitor-1", isPrimary: true }],
    ratingsAverage: 4.7,
    ratingsQuantity: 96,
    tags: ["electronics", "monitor", "display", "bestseller"],
    featured: true,
  },
  {
    title: "AeroShield 4K Drone Explorer",
    category: "Electronics",
    brand: "Nova Tech",
    description: "Compact ultralight folding drone equipped with a 3-axis stabilized 4K HDR camera, 35-minute flight time, optical obstacle avoidance, and 10km live video transmission.",
    basePrice: 38999,
    baseDiscountPrice: 32499,
    stock: 14,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1507582020474-9a35b7d455d9?auto=format&fit=crop&w=900&q=80", publicId: "prod/drone-1", isPrimary: true }],
    ratingsAverage: 4.9,
    ratingsQuantity: 88,
    tags: ["electronics", "drone", "camera", "deals", "featured"],
    featured: true,
  },
  {
    title: "CorePulse 1000W Smart Power Station",
    category: "Electronics",
    brand: "Nova Tech",
    description: "1024Wh LiFePO4 battery generator with 1000W pure sine wave AC output, 100W USB-C PD charging, and high-efficiency solar recharge input for outdoor excursions.",
    basePrice: 56999,
    baseDiscountPrice: 48999,
    stock: 8,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=900&q=80", publicId: "prod/power-1", isPrimary: true }],
    ratingsAverage: 4.9,
    ratingsQuantity: 42,
    tags: ["electronics", "battery", "power", "travel"],
    featured: true,
  },
  {
    title: "Horizon Ultra-Short Throw 4K Smart Projector",
    category: "Electronics",
    brand: "Nova Tech",
    description: "Laser cinema projector capable of projecting up to 150-inch 4K HDR visuals from just inches away, featuring Harman Kardon integrated acoustics and Android TV.",
    basePrice: 89999,
    baseDiscountPrice: 74999,
    stock: 6,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=80", publicId: "prod/projector-1", isPrimary: true }],
    ratingsAverage: 4.9,
    ratingsQuantity: 31,
    tags: ["electronics", "cinema", "projector", "luxury"],
    featured: true,
  },

  // =========================================================================
  // 2. AUDIO & SOUND (15 Products: <1k, 1k-3k, 3k-8k, >8k)
  // =========================================================================
  {
    title: "Hi-Res Lossless 3.5mm Earphone DAC Adapter",
    category: "Audio & Sound",
    brand: "Aether Audio",
    description: "32-bit/384kHz audiophile grade USB-C to 3.5mm headphone amplifier adapter with Realtek ALC5686 DAC chip and braided Kevlar wire.",
    basePrice: 899,
    baseDiscountPrice: 649,
    stock: 90,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80", publicId: "prod/dac-1", isPrimary: true }],
    ratingsAverage: 4.7,
    ratingsQuantity: 280,
    tags: ["audio", "dac", "adapter", "deals"],
    featured: false,
  },
  {
    title: "In-Ear Dynamic Bass Earphones with Mic",
    category: "Audio & Sound",
    brand: "Aether Audio",
    description: "10mm dynamic driver wired in-ear monitors with tangle-free flat cable, HD condenser microphone, and noise-isolating silicone ear tips.",
    basePrice: 999,
    baseDiscountPrice: 799,
    stock: 75,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=900&q=80", publicId: "prod/wired-1", isPrimary: true }],
    ratingsAverage: 4.6,
    ratingsQuantity: 350,
    tags: ["audio", "earphones", "wired", "sale"],
    featured: false,
  },
  {
    title: "AeroBeats Neckband Wireless Earphones",
    category: "Audio & Sound",
    brand: "Aether Audio",
    description: "Flexible silicone neckband with magnetic earbuds, magnetic auto-pause, low-latency gaming mode, and 30-hour battery life.",
    basePrice: 1999,
    baseDiscountPrice: 1499,
    stock: 75,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=900&q=80", publicId: "prod/neckband-1", isPrimary: true }],
    ratingsAverage: 4.4,
    ratingsQuantity: 610,
    tags: ["audio", "neckband", "budget", "sale"],
    featured: false,
  },
  {
    title: "Aether Pods Compact Charging Case Earphones",
    category: "Audio & Sound",
    brand: "Aether Audio",
    description: "Featherlight everyday earphones with quad microphones for crystal-clear calls, touch controls, and instantaneous Bluetooth device pairing.",
    basePrice: 3299,
    baseDiscountPrice: 2399,
    stock: 65,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=900&q=80", publicId: "prod/pods-1", isPrimary: true }],
    ratingsAverage: 4.5,
    ratingsQuantity: 520,
    tags: ["audio", "earbuds", "budget", "bestseller"],
    featured: false,
  },
  {
    title: "BoomTrek Waterproof Outdoor Speaker",
    category: "Audio & Sound",
    brand: "Aether Audio",
    description: "IP67 submersible rugged outdoor speaker with 360-degree bass radiator, integrated silicone carry strap, and 24-hour party playback.",
    basePrice: 3999,
    baseDiscountPrice: 2899,
    stock: 50,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=80", publicId: "prod/outdoor-spk-1", isPrimary: true }],
    ratingsAverage: 4.6,
    ratingsQuantity: 210,
    tags: ["audio", "speaker", "waterproof", "sale"],
    featured: false,
  },
  {
    title: "Pulse Buds True Wireless Earbuds",
    category: "Audio & Sound",
    brand: "Aether Audio",
    description: "Compact wireless in-ear monitors with 42dB intelligent adaptive noise cancellation, transparency audio pass-through, and IPX5 sweatproof protection.",
    basePrice: 5999,
    baseDiscountPrice: 4299,
    stock: 48,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=900&q=80", publicId: "prod/earbuds-1", isPrimary: true }],
    ratingsAverage: 4.7,
    ratingsQuantity: 290,
    tags: ["audio", "earbuds", "wireless", "sale"],
    featured: false,
  },
  {
    title: "SoundBox Heritage Wooden Bluetooth Speaker",
    category: "Audio & Sound",
    brand: "Aether Audio",
    description: "Vintage-styled 40W stereo loudspeaker handcrafted from solid walnut wood casing with analog brass control dials and modern Bluetooth 5.3 connectivity.",
    basePrice: 8999,
    baseDiscountPrice: 6999,
    stock: 22,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=900&q=80", publicId: "prod/speaker-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 154,
    tags: ["audio", "speaker", "vintage", "deals"],
    featured: true,
  },
  {
    title: "VocalPure Dynamic Podcast Microphone",
    category: "Audio & Sound",
    brand: "Signal Works",
    description: "Cardioid dynamic vocal microphone designed for podcasting, voiceover, and livestreaming with internal pneumatic shock mounting.",
    basePrice: 8499,
    baseDiscountPrice: 6999,
    stock: 24,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=900&q=80", publicId: "prod/vocal-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 91,
    tags: ["audio", "podcast", "microphone"],
    featured: false,
  },
  {
    title: "Horizon Compact TV Soundbar with Subwoofer",
    category: "Audio & Sound",
    brand: "Aether Audio",
    description: "Slimline 120W soundbar with dedicated wireless subwoofer, Bluetooth 5.3, optical audio input, and HDMI ARC support for cinema sound.",
    basePrice: 7999,
    baseDiscountPrice: 6499,
    stock: 25,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=900&q=80", publicId: "prod/hsoundbar-1", isPrimary: true }],
    ratingsAverage: 4.7,
    ratingsQuantity: 140,
    tags: ["audio", "soundbar", "tv", "deals"],
    featured: false,
  },
  {
    title: "SoundBar Pro 2.1 Virtual Dolby Atmos",
    category: "Audio & Sound",
    brand: "Aether Audio",
    description: "Slimline home theater soundbar with wireless down-firing subwoofer, HDMI eARC support, and multi-room optical audio playback.",
    basePrice: 12499,
    baseDiscountPrice: 9999,
    stock: 18,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=900&q=80", publicId: "prod/soundbar-1", isPrimary: true }],
    ratingsAverage: 4.7,
    ratingsQuantity: 112,
    tags: ["audio", "soundbar", "homecinema"],
    featured: false,
  },
  {
    title: "Aether Pro Wireless ANC Headphones",
    category: "Audio & Sound",
    brand: "Aether Audio",
    description: "Flagship hybrid active noise cancelling headphones featuring custom 40mm graphene drivers, LDAC high-res wireless audio codec, and 50-hour ultra-long battery life.",
    basePrice: 14999,
    baseDiscountPrice: 11999,
    stock: 26,
    hasVariants: true,
    variants: [
      {
        sku: "AETH-ANC-BLK",
        attributes: { color: "Obsidian Black", material: "Memory Foam & Leather" },
        price: 14999,
        discountPrice: 11999,
        stock: 14,
        image: { url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80", publicId: "prod/anc-blk" },
      },
      {
        sku: "AETH-ANC-SLV",
        attributes: { color: "Starlight Silver", material: "Memory Foam & Leather" },
        price: 14999,
        discountPrice: 11999,
        stock: 12,
        image: { url: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=900&q=80", publicId: "prod/anc-slv" },
      },
    ],
    images: [
      { url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80", publicId: "prod/headphone-1", isPrimary: true },
      { url: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=900&q=80", publicId: "prod/headphone-2", isPrimary: false },
    ],
    ratingsAverage: 4.9,
    ratingsQuantity: 380,
    tags: ["audio", "headphones", "wireless", "deals", "bestseller"],
    featured: true,
  },
  {
    title: "VinylWave Classic Belt-Drive Turntable",
    category: "Audio & Sound",
    brand: "Hearth & Co",
    description: "Precision belt-drive analog turntable with Audio-Technica magnetic phono cartridge, built-in switchable pre-amp, and Bluetooth vinyl streaming.",
    basePrice: 15999,
    baseDiscountPrice: 12999,
    stock: 16,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=900&q=80", publicId: "prod/turntable-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 73,
    tags: ["audio", "turntable", "vinyl", "vintage"],
    featured: false,
  },
  {
    title: "StudioReference 5 Inch Active Monitors",
    category: "Audio & Sound",
    brand: "Signal Works",
    description: "Pair of bi-amplified nearfield studio monitors tuned with kevlar composite woofers for clinical sound transparency and accurate music production mixing.",
    basePrice: 19999,
    baseDiscountPrice: 16499,
    stock: 12,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1520170350707-b2da59970118?auto=format&fit=crop&w=900&q=80", publicId: "prod/studio-1", isPrimary: true }],
    ratingsAverage: 4.9,
    ratingsQuantity: 47,
    tags: ["audio", "studio", "monitors", "pro"],
    featured: false,
  },
  {
    title: "MasterClass Open-Back Planar Magnetic Headphones",
    category: "Audio & Sound",
    brand: "Aether Audio",
    description: "Reference audiophile headphones with ultra-thin nano-scale planar drivers, CNC machined aluminum earcups, and lambskin suspension headband.",
    basePrice: 34999,
    baseDiscountPrice: 27999,
    stock: 8,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80", publicId: "prod/planar-1", isPrimary: true }],
    ratingsAverage: 4.9,
    ratingsQuantity: 28,
    tags: ["audio", "headphones", "audiophile", "luxury"],
    featured: true,
  },
  {
    title: "Audiophile Vacuum Tube Preamplifier",
    category: "Audio & Sound",
    brand: "Aether Audio",
    description: "Handcrafted hybrid vacuum tube amplifier with twin 6N3 tubes delivering analog warmth, optical DAC inputs, and high-fidelity output.",
    basePrice: 46999,
    baseDiscountPrice: 38999,
    stock: 5,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=900&q=80", publicId: "prod/tube-1", isPrimary: true }],
    ratingsAverage: 4.9,
    ratingsQuantity: 18,
    tags: ["audio", "amplifier", "tube", "audiophile"],
    featured: true,
  },

  // =========================================================================
  // 3. FASHION & APPAREL (15 Products: <1k, 1k-3k, 3k-8k, >8k)
  // =========================================================================
  {
    title: "Organic Combed Cotton Ribbed Beanie",
    category: "Fashion",
    brand: "Atelier One",
    description: "Double-layered fisherman style cuff beanie knitted from 100% organic combed cotton with itch-free breathable comfort.",
    basePrice: 899,
    baseDiscountPrice: 699,
    stock: 85,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=900&q=80", publicId: "prod/beanie-1", isPrimary: true }],
    ratingsAverage: 4.7,
    ratingsQuantity: 210,
    tags: ["fashion", "beanie", "winter", "deals"],
    featured: false,
  },
  {
    title: "Seamless Bamboo Fiber Crew Socks (Pack of 3)",
    category: "Fashion",
    brand: "Atelier One",
    description: "Moisture-wicking anti-odor crew socks crafted with reinforced heels, seamless toes, and cushioned plantar support.",
    basePrice: 799,
    baseDiscountPrice: 599,
    stock: 95,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80", publicId: "prod/socks-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 430,
    tags: ["fashion", "socks", "basics", "sale"],
    featured: false,
  },
  {
    title: "Classic Oxford Button-Down Shirt",
    category: "Fashion",
    brand: "Atelier One",
    description: "Heavy oxford cloth weave with authentic roll button-down collar, curved hem, and box pleat for everyday smart-casual dressing.",
    basePrice: 2299,
    baseDiscountPrice: 1799,
    stock: 50,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&w=900&q=80", publicId: "prod/oxford-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 280,
    tags: ["fashion", "shirt", "formal", "bestseller"],
    featured: false,
  },
  {
    title: "Atelier Relaxed Linen Shirt",
    category: "Fashion",
    brand: "Atelier One",
    description: "Tailored from 100% sustainably harvested French flax linen with breathable open collar, mother-of-pearl buttons, and relaxed drape.",
    basePrice: 2899,
    baseDiscountPrice: 2199,
    stock: 45,
    hasVariants: true,
    variants: [
      {
        sku: "ATL-LIN-WHT-M",
        attributes: { color: "Off-White", size: "M", material: "Pure Linen" },
        price: 2899,
        discountPrice: 2199,
        stock: 22,
        image: { url: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=900&q=80", publicId: "prod/linen-wht" },
      },
      {
        sku: "ATL-LIN-NVY-L",
        attributes: { color: "Navy Blue", size: "L", material: "Pure Linen" },
        price: 2899,
        discountPrice: 2199,
        stock: 23,
        image: { url: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=900&q=80", publicId: "prod/linen-nvy" },
      },
    ],
    images: [
      { url: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=900&q=80", publicId: "prod/shirt-1", isPrimary: true },
      { url: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=900&q=80", publicId: "prod/shirt-2", isPrimary: false },
    ],
    ratingsAverage: 4.8,
    ratingsQuantity: 185,
    tags: ["fashion", "shirt", "linen", "summer", "bestseller"],
    featured: true,
  },
  {
    title: "Everyday Supima Cotton Crewneck Tee (Pack of 3)",
    category: "Fashion",
    brand: "Atelier One",
    description: "Ultra-soft staple tees made from extra-long staple Supima cotton that resists fading and pilling through hundreds of washes.",
    basePrice: 2499,
    baseDiscountPrice: 1899,
    stock: 60,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80", publicId: "prod/tee-1", isPrimary: true }],
    ratingsAverage: 4.9,
    ratingsQuantity: 420,
    tags: ["fashion", "tshirt", "basics", "bestseller"],
    featured: false,
  },
  {
    title: "Urban Technical Cargo Joggers",
    category: "Fashion",
    brand: "Atelier One",
    description: "DWR water-resistant stretch ripstop cargo pants with articulated knee seams, deep zip pockets, and elasticated ankle cuffs.",
    basePrice: 3299,
    baseDiscountPrice: 2499,
    stock: 35,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1517445312882-bc9910d016b7?auto=format&fit=crop&w=900&q=80", publicId: "prod/cargo-1", isPrimary: true }],
    ratingsAverage: 4.7,
    ratingsQuantity: 195,
    tags: ["fashion", "cargos", "streetwear"],
    featured: false,
  },
  {
    title: "Heavyweight Organic Cotton Hoodie",
    category: "Fashion",
    brand: "Atelier One",
    description: "450 GSM combed organic cotton fleece pullover hoodie with double-layered hood, ribbed side panels, and pre-shrunk premium fit.",
    basePrice: 3499,
    baseDiscountPrice: 2699,
    stock: 40,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=900&q=80", publicId: "prod/hoodie-1", isPrimary: true }],
    ratingsAverage: 4.7,
    ratingsQuantity: 310,
    tags: ["fashion", "hoodie", "streetwear", "bestseller"],
    featured: false,
  },
  {
    title: "Tailored Smart Wool-Blend Trousers",
    category: "Fashion",
    brand: "Atelier One",
    description: "Modern tapered dress trousers with elasticated hidden waistband, crease-resistant stretch blend, and clean front pleats.",
    basePrice: 3799,
    baseDiscountPrice: 2999,
    stock: 30,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=900&q=80", publicId: "prod/trousers-1", isPrimary: true }],
    ratingsAverage: 4.6,
    ratingsQuantity: 145,
    tags: ["fashion", "trousers", "formal"],
    featured: false,
  },
  {
    title: "Merino Wool Knit Crewneck Sweater",
    category: "Fashion",
    brand: "Atelier One",
    description: "100% fine Australian Merino wool sweater with natural temperature-regulating microfibers and ribbed cuff accents.",
    basePrice: 4599,
    baseDiscountPrice: 3699,
    stock: 26,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=900&q=80", publicId: "prod/sweater-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 110,
    tags: ["fashion", "sweater", "winter", "deals"],
    featured: false,
  },
  {
    title: "Reversible Bomber Flight Jacket",
    category: "Fashion",
    brand: "Atelier One",
    description: "Classic aviation MA-1 flight silhouette with water-repellent nylon shell, lightweight thermal insulation, and rescue orange interior.",
    basePrice: 5499,
    baseDiscountPrice: 4299,
    stock: 22,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=900&q=80", publicId: "prod/bomber-1", isPrimary: true }],
    ratingsAverage: 4.6,
    ratingsQuantity: 84,
    tags: ["fashion", "bomber", "jacket"],
    featured: false,
  },
  {
    title: "Heritage Selvedge Denim Jacket",
    category: "Fashion",
    brand: "Atelier One",
    description: "Heavyweight 14oz raw Japanese selvedge denim jacket finished with custom engraved copper rivets, reinforced bar tacks, and classic chest pockets.",
    basePrice: 5999,
    baseDiscountPrice: 4799,
    stock: 25,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=900&q=80", publicId: "prod/denim-1", isPrimary: true }],
    ratingsAverage: 4.9,
    ratingsQuantity: 92,
    tags: ["fashion", "jacket", "denim", "featured"],
    featured: true,
  },
  {
    title: "Japanese Raw Selvedge Slim Jeans",
    category: "Fashion",
    brand: "Atelier One",
    description: "Shuttle-loom woven 13.5oz indigo selvedge denim jeans with red line selvedge ID, donut buttons, and genuine leather back patch.",
    basePrice: 5699,
    baseDiscountPrice: 4499,
    stock: 30,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&w=900&q=80", publicId: "prod/jeans-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 160,
    tags: ["fashion", "denim", "jeans", "bestseller"],
    featured: false,
  },
  {
    title: "Tailored Double-Breasted Wool Peacoat",
    category: "Fashion",
    brand: "Atelier One",
    description: "Substantial 800 GSM wool-blend nautical peacoat with anchor-embossed horn buttons, welted handwarmer pockets, and quilted thermal lining.",
    basePrice: 8499,
    baseDiscountPrice: 6999,
    stock: 15,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=900&q=80", publicId: "prod/peacoat-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 76,
    tags: ["fashion", "coat", "winter", "deals"],
    featured: false,
  },
  {
    title: "Minimalist Trench Coat",
    category: "Fashion",
    brand: "Atelier One",
    description: "Water-repellent double-breasted cotton-gabardine trench coat with storm flap, removable waist belt, and satin interior lining.",
    basePrice: 11999,
    baseDiscountPrice: 8999,
    stock: 18,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=900&q=80", publicId: "prod/trench-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 67,
    tags: ["fashion", "coat", "winter", "deals"],
    featured: false,
  },
  {
    title: "Italian Lambskin Leather Biker Jacket",
    category: "Fashion",
    brand: "Atelier One",
    description: "Butter-soft full-grain Italian lambskin leather motorcycle jacket with asymmetrical silver YKK Excella zippers and belted hem.",
    basePrice: 24999,
    baseDiscountPrice: 18999,
    stock: 10,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=900&q=80", publicId: "prod/leather-jacket-1", isPrimary: true }],
    ratingsAverage: 4.9,
    ratingsQuantity: 44,
    tags: ["fashion", "leather", "jacket", "luxury"],
    featured: true,
  },

  // =========================================================================
  // 4. FOOTWEAR (15 Products: <1k, 1k-3k, 3k-8k, >8k)
  // =========================================================================
  {
    title: "Memory Foam Cushioned Arch-Support Insoles",
    category: "Footwear",
    brand: "Stride Lab",
    description: "Orthopedic shock-absorbing shoe insoles with deep heel cup, ventilated pores, and antimicrobial top layer.",
    basePrice: 799,
    baseDiscountPrice: 599,
    stock: 90,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80", publicId: "prod/insole-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 310,
    tags: ["footwear", "insoles", "accessories", "deals"],
    featured: false,
  },
  {
    title: "Anti-Slip Textured Shower & Spa Slides",
    category: "Footwear",
    brand: "Stride Lab",
    description: "Quick-drying EVA bathroom and pool slides with drain holes, anti-slip grooved tread, and soft footbed.",
    basePrice: 899,
    baseDiscountPrice: 699,
    stock: 75,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&w=900&q=80", publicId: "prod/spaslide-1", isPrimary: true }],
    ratingsAverage: 4.6,
    ratingsQuantity: 240,
    tags: ["footwear", "slides", "summer", "sale"],
    featured: false,
  },
  {
    title: "Everyday Slide Recovery Sandals",
    category: "Footwear",
    brand: "Stride Lab",
    description: "Ergonomic arch-support slides crafted from soft EVA foam designed for post-workout athletic recovery and poolside lounging.",
    basePrice: 1799,
    baseDiscountPrice: 1299,
    stock: 55,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&w=900&q=80", publicId: "prod/slides-1", isPrimary: true }],
    ratingsAverage: 4.5,
    ratingsQuantity: 340,
    tags: ["footwear", "slides", "summer"],
    featured: false,
  },
  {
    title: "Minimalist Canvas Low-Top Sneakers",
    category: "Footwear",
    brand: "Stride Lab",
    description: "Breathable organic cotton canvas trainers with durable rubber toe bumper and OrthoLite comfort insole.",
    basePrice: 2899,
    baseDiscountPrice: 2199,
    stock: 42,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=900&q=80", publicId: "prod/canvas-1", isPrimary: true }],
    ratingsAverage: 4.7,
    ratingsQuantity: 285,
    tags: ["footwear", "canvas", "basics"],
    featured: false,
  },
  {
    title: "Lightweight Breathable Mesh Gym Runners",
    category: "Footwear",
    brand: "Stride Lab",
    description: "Seamless engineered mesh training shoes with ultra-cushioned EVA foam sole, non-marking rubber pods, and padded heel counter.",
    basePrice: 3199,
    baseDiscountPrice: 2499,
    stock: 40,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=900&q=80", publicId: "prod/gymrunner-1", isPrimary: true }],
    ratingsAverage: 4.6,
    ratingsQuantity: 190,
    tags: ["footwear", "runners", "gym", "sale"],
    featured: false,
  },
  {
    title: "Retro Court Leather High-Top Trainers",
    category: "Footwear",
    brand: "Stride Lab",
    description: "Vintage 1980s basketball-inspired high-top trainers with perforated toe box, padded collar, and vulcanized rubber cupsole.",
    basePrice: 4999,
    baseDiscountPrice: 3899,
    stock: 32,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1512374382149-233c42b6a83b?auto=format&fit=crop&w=900&q=80", publicId: "prod/hightop-1", isPrimary: true }],
    ratingsAverage: 4.6,
    ratingsQuantity: 210,
    tags: ["footwear", "sneakers", "streetwear", "sale"],
    featured: false,
  },
  {
    title: "CloudWalk Pro Cushion Sneakers",
    category: "Footwear",
    brand: "Stride Lab",
    description: "Ultra-responsive nitrogen-infused foam midsole paired with engineered breathable knit upper for all-day walking and high-energy running.",
    basePrice: 5499,
    baseDiscountPrice: 4299,
    stock: 38,
    hasVariants: true,
    variants: [
      {
        sku: "CWK-SNK-WHT-9",
        attributes: { color: "Cloud White", size: "UK 9", material: "Breathable Knit" },
        price: 5499,
        discountPrice: 4299,
        stock: 20,
        image: { url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80", publicId: "prod/snk-wht" },
      },
      {
        sku: "CWK-SNK-RED-10",
        attributes: { color: "Crimson Red", size: "UK 10", material: "Breathable Knit" },
        price: 5499,
        discountPrice: 4299,
        stock: 18,
        image: { url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80", publicId: "prod/snk-red" },
      },
    ],
    images: [{ url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80", publicId: "prod/sneaker-1", isPrimary: true }],
    ratingsAverage: 4.9,
    ratingsQuantity: 490,
    tags: ["footwear", "sneakers", "running", "deals", "bestseller"],
    featured: true,
  },
  {
    title: "Suede Penny Loafers Handstitched",
    category: "Footwear",
    brand: "Stride Lab",
    description: "Supple calfskin suede loafers with handstitched apron, memory foam padded footbed, and unlined construction for unmatched sockless comfort.",
    basePrice: 5999,
    baseDiscountPrice: 4799,
    stock: 28,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1614252369475-531eba835eb1?auto=format&fit=crop&w=900&q=80", publicId: "prod/loafer-1", isPrimary: true }],
    ratingsAverage: 4.7,
    ratingsQuantity: 160,
    tags: ["footwear", "loafers", "formal"],
    featured: false,
  },
  {
    title: "Classic Suede Chukka Desert Boots",
    category: "Footwear",
    brand: "Stride Lab",
    description: "Ankle-high 3-eyelet desert boots with premium water-resistant suede upper and natural plantation crepe rubber sole.",
    basePrice: 6999,
    baseDiscountPrice: 5499,
    stock: 22,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1638247025967-b4e38f787b76?auto=format&fit=crop&w=900&q=80", publicId: "prod/chukka-1", isPrimary: true }],
    ratingsAverage: 4.7,
    ratingsQuantity: 110,
    tags: ["footwear", "boots", "suede", "deals"],
    featured: false,
  },
  {
    title: "TerraGrip Waterproof Trail Running Shoes",
    category: "Footwear",
    brand: "Stride Lab",
    description: "Rugged Vibram Megagrip lugged outsole paired with GORE-TEX waterproof breathable membrane and rock protection plate for muddy mountain trails.",
    basePrice: 6999,
    baseDiscountPrice: 5499,
    stock: 24,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=900&q=80", publicId: "prod/trail-1", isPrimary: true }],
    ratingsAverage: 4.7,
    ratingsQuantity: 88,
    tags: ["footwear", "trail", "running", "deals"],
    featured: false,
  },
  {
    title: "Double Monk Strap Burnished Leather Shoes",
    category: "Footwear",
    brand: "Stride Lab",
    description: "Handcrafted calfskin leather double monk strap dress shoes with polished brass hardware, Goodyear welted sole, and cushioned footbed.",
    basePrice: 7499,
    baseDiscountPrice: 5999,
    stock: 20,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=900&q=80", publicId: "prod/monk-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 115,
    tags: ["footwear", "formal", "leather", "shoes"],
    featured: false,
  },
  {
    title: "Alpine Explorer Waterproof Hiking Boots",
    category: "Footwear",
    brand: "Stride Lab",
    description: "High-ankle mountaineering boots with rubber rand scuff guards, steel shank support, and thermal fleece insulation.",
    basePrice: 9499,
    baseDiscountPrice: 7699,
    stock: 16,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=900&q=80", publicId: "prod/hiking-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 95,
    tags: ["footwear", "boots", "hiking", "deals"],
    featured: false,
  },
  {
    title: "Heritage Full-Grain Leather Chelsea Boots",
    category: "Footwear",
    brand: "Stride Lab",
    description: "Handcrafted from Italian full-grain pull-up leather with Goodyear welted construction, elasticated side gussets, and durable rubber commando sole.",
    basePrice: 11499,
    baseDiscountPrice: 8999,
    stock: 20,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1638247025967-b4e38f787b76?auto=format&fit=crop&w=900&q=80", publicId: "prod/chelsea-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 125,
    tags: ["footwear", "boots", "leather", "featured"],
    featured: true,
  },
  {
    title: "AeroVelocity Carbon Plated Race Runners",
    category: "Footwear",
    brand: "Stride Lab",
    description: "Super-responsive Pebax supercritical foam paired with a full-length carbon fiber propulsion plate engineered for marathon personal bests.",
    basePrice: 11999,
    baseDiscountPrice: 9499,
    stock: 15,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=900&q=80", publicId: "prod/carbon-1", isPrimary: true }],
    ratingsAverage: 4.9,
    ratingsQuantity: 88,
    tags: ["footwear", "running", "marathon", "bestseller"],
    featured: true,
  },
  {
    title: "Goodyear Welted Handcrafted Oxford Shoes",
    category: "Footwear",
    brand: "Stride Lab",
    description: "Handcrafted black box calf leather cap-toe formal Oxford shoes with channel-stitched leather soles and cork bed filling.",
    basePrice: 15999,
    baseDiscountPrice: 12499,
    stock: 12,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=900&q=80", publicId: "prod/oxford-shoe-1", isPrimary: true }],
    ratingsAverage: 4.9,
    ratingsQuantity: 52,
    tags: ["footwear", "formal", "oxford", "luxury"],
    featured: true,
  },

  // =========================================================================
  // 5. ACCESSORIES (15 Products: <1k, 1k-3k, 3k-8k, >8k)
  // =========================================================================
  {
    title: "Stainless Steel Minimalist Money Clip",
    category: "Accessories",
    brand: "Northstar",
    description: "Brushed 316L stainless steel ultra-slim money clip capable of holding up to 15 folded banknotes and 5 credit cards.",
    basePrice: 699,
    baseDiscountPrice: 499,
    stock: 80,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=900&q=80", publicId: "prod/moneyclip-1", isPrimary: true }],
    ratingsAverage: 4.6,
    ratingsQuantity: 180,
    tags: ["accessories", "wallet", "edc"],
    featured: false,
  },
  {
    title: "Leather Key Organizer Loop with Brass Hardware",
    category: "Accessories",
    brand: "Northstar",
    description: "Vegetable-tanned full-grain leather key fob with solid antiqued brass screw post that keeps up to 7 keys silent and pocket-friendly.",
    basePrice: 799,
    baseDiscountPrice: 599,
    stock: 70,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1582845512747-e42001c95638?auto=format&fit=crop&w=900&q=80", publicId: "prod/keyfob-1", isPrimary: true }],
    ratingsAverage: 4.7,
    ratingsQuantity: 215,
    tags: ["accessories", "edc", "leather", "deals"],
    featured: false,
  },
  {
    title: "Microfiber Precision Eyewear Cleaning Kit",
    category: "Accessories",
    brand: "Northstar",
    description: "Anti-static optical lens cleaner spray with dual oversized lint-free microfiber polishing cloths and mini aluminum screwdriver tool.",
    basePrice: 599,
    baseDiscountPrice: 399,
    stock: 95,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=900&q=80", publicId: "prod/cleankit-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 150,
    tags: ["accessories", "eyewear", "care", "sale"],
    featured: false,
  },
  {
    title: "Insulated Stainless Steel Thermal Flask 750ml",
    category: "Accessories",
    brand: "Northstar",
    description: "Double-wall vacuum insulated 18/8 food-grade stainless steel bottle that keeps drinks cold for 24 hours or piping hot for 12 hours.",
    basePrice: 1499,
    baseDiscountPrice: 1099,
    stock: 65,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=80", publicId: "prod/flask-1", isPrimary: true }],
    ratingsAverage: 4.7,
    ratingsQuantity: 390,
    tags: ["accessories", "bottle", "lifestyle"],
    featured: false,
  },
  {
    title: "Apex Titanium Key Carabiner & Multi-Tool",
    category: "Accessories",
    brand: "Northstar",
    description: "Grade 5 titanium CNC-machined EDC carabiner clip with integrated bottle opener, pry bar, hex wrenches, and anti-lost locking gate.",
    basePrice: 1599,
    baseDiscountPrice: 1199,
    stock: 60,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1582845512747-e42001c95638?auto=format&fit=crop&w=900&q=80", publicId: "prod/keytool-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 230,
    tags: ["accessories", "edc", "titanium", "tools"],
    featured: false,
  },
  {
    title: "Slim Bifold Leather Wallet with RFID Shield",
    category: "Accessories",
    brand: "Northstar",
    description: "Full-grain vegetable-tanned leather wallet with quick-draw card slot, cash compartment, and integrated electromagnetic RFID blocking barrier.",
    basePrice: 1899,
    baseDiscountPrice: 1399,
    stock: 50,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=900&q=80", publicId: "prod/wallet-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 480,
    tags: ["accessories", "wallet", "leather", "bestseller"],
    featured: false,
  },
  {
    title: "Braided Italian Leather Belt with Brushed Brass",
    category: "Accessories",
    brand: "Northstar",
    description: "Hand-plaited genuine leather belt with solid brass buckle that offers a custom micro-adjustable fit without standard prong holes.",
    basePrice: 1999,
    baseDiscountPrice: 1499,
    stock: 40,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80", publicId: "prod/belt-1", isPrimary: true }],
    ratingsAverage: 4.6,
    ratingsQuantity: 180,
    tags: ["accessories", "belt", "leather"],
    featured: false,
  },
  {
    title: "Voyager Full-Grain Leather Travel Passport Folio",
    category: "Accessories",
    brand: "Northstar",
    description: "Handmade vegetable-tanned leather travel folio with dual passport slots, boarding pass flap, SIM card ejector slot, and magnetic pen holder.",
    basePrice: 2499,
    baseDiscountPrice: 1899,
    stock: 40,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=900&q=80", publicId: "prod/passport-1", isPrimary: true }],
    ratingsAverage: 4.9,
    ratingsQuantity: 280,
    tags: ["accessories", "travel", "leather", "bestseller"],
    featured: true,
  },
  {
    title: "Orbit Polarized Aviator Sunglasses",
    category: "Accessories",
    brand: "Northstar",
    description: "Lightweight titanium wireframe aviators with UV400 polarized mineral glass lenses and anti-reflective internal coating.",
    basePrice: 2999,
    baseDiscountPrice: 2299,
    stock: 45,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=900&q=80", publicId: "prod/sunglasses-1", isPrimary: true }],
    ratingsAverage: 4.7,
    ratingsQuantity: 215,
    tags: ["accessories", "sunglasses", "summer", "sale"],
    featured: false,
  },
  {
    title: "Solstice Acetate Polarized Sunglasses",
    category: "Accessories",
    brand: "Northstar",
    description: "Handcrafted Italian bio-acetate frames fitted with category 3 polarized gradient lenses and 5-barrel custom stainless hinges.",
    basePrice: 3299,
    baseDiscountPrice: 2499,
    stock: 35,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=900&q=80", publicId: "prod/wayfarer-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 175,
    tags: ["accessories", "sunglasses", "summer", "deals"],
    featured: false,
  },
  {
    title: "Vanguard Sterling Silver Minimal Cuff Bracelet",
    category: "Accessories",
    brand: "Northstar",
    description: "Solid 925 sterling silver hammered cuff bracelet with brushed matte finish and subtle tapered ends for a bespoke wrist profile.",
    basePrice: 3499,
    baseDiscountPrice: 2799,
    stock: 25,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1611591475102-4fa01202e860?auto=format&fit=crop&w=900&q=80", publicId: "prod/cuff-1", isPrimary: true }],
    ratingsAverage: 4.7,
    ratingsQuantity: 95,
    tags: ["accessories", "jewelry", "silver"],
    featured: false,
  },
  {
    title: "Aurora Minimalist Sapphire Watch",
    category: "Accessories",
    brand: "Northstar",
    description: "Sleek 38mm stainless steel case with scratch-resistant sapphire crystal glass, Japanese Miyota quartz movement, and interchangeable genuine Horween leather strap.",
    basePrice: 4999,
    baseDiscountPrice: 3899,
    stock: 30,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80", publicId: "prod/watch-1", isPrimary: true }],
    ratingsAverage: 4.9,
    ratingsQuantity: 340,
    tags: ["accessories", "watches", "luxury", "bestseller"],
    featured: true,
  },
  {
    title: "Damascus Steel Handcrafted Folding Knife",
    category: "Accessories",
    brand: "Northstar",
    description: "67-layer Damascus steel drop-point blade with smooth ball-bearing flipper pivot, liner lock, and contoured olive wood handle scales.",
    basePrice: 5499,
    baseDiscountPrice: 4299,
    stock: 20,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1582845512747-e42001c95638?auto=format&fit=crop&w=900&q=80", publicId: "prod/knife-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 112,
    tags: ["accessories", "edc", "knife", "craft"],
    featured: false,
  },
  {
    title: "Automatic Dual Watch Winder Showcase",
    category: "Accessories",
    brand: "Northstar",
    description: "Ultra-quiet Japanese Mabuchi motor watch winder with piano black lacquered wood finish, soft blue LED illumination, and programmable rotation cycles.",
    basePrice: 7499,
    baseDiscountPrice: 5999,
    stock: 14,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=900&q=80", publicId: "prod/winder-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 65,
    tags: ["accessories", "watches", "luxury", "winder"],
    featured: false,
  },
  {
    title: "Metro Chronograph Automatic Watch",
    category: "Accessories",
    brand: "Northstar",
    description: "Exhibition caseback automatic chronograph with 42-hour power reserve, tachymeter bezel, date complication, and 100m water resistance.",
    basePrice: 12999,
    baseDiscountPrice: 9999,
    stock: 15,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=900&q=80", publicId: "prod/chrono-1", isPrimary: true }],
    ratingsAverage: 4.9,
    ratingsQuantity: 110,
    tags: ["accessories", "watches", "luxury", "featured"],
    featured: true,
  },

  // =========================================================================
  // 6. BAGS & TRAVEL (15 Products: <1k, 1k-3k, 3k-8k, >8k)
  // =========================================================================
  {
    title: "Waterproof Compact Passport & Card Neck Pouch",
    category: "Bags & Travel",
    brand: "Field Notes",
    description: "Ultra-lightweight ripstop nylon neck wallet with RFID blocking slots, breathable mesh back panel, and adjustable neck cord.",
    basePrice: 799,
    baseDiscountPrice: 599,
    stock: 80,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=900&q=80", publicId: "prod/neckpouch-1", isPrimary: true }],
    ratingsAverage: 4.7,
    ratingsQuantity: 190,
    tags: ["bags", "travel", "wallet", "deals"],
    featured: false,
  },
  {
    title: "TSA-Approved Heavy-Duty Luggage Lock (Pair)",
    category: "Bags & Travel",
    brand: "Field Notes",
    description: "Solid zinc alloy 4-digit resettable combination padlock with open alert indicator and flexible steel shackle.",
    basePrice: 899,
    baseDiscountPrice: 699,
    stock: 85,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?auto=format&fit=crop&w=900&q=80", publicId: "prod/tsalock-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 320,
    tags: ["bags", "travel", "security", "sale"],
    featured: false,
  },
  {
    title: "Compression Travel Packing Cubes (Set of 3)",
    category: "Bags & Travel",
    brand: "Field Notes",
    description: "Double zipper compression cubes made from ultralight water-resistant ripstop nylon that saves up to 60% suitcase space.",
    basePrice: 1199,
    baseDiscountPrice: 899,
    stock: 75,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80", publicId: "prod/cubes-1", isPrimary: true }],
    ratingsAverage: 4.9,
    ratingsQuantity: 410,
    tags: ["bags", "travel", "organization", "bestseller"],
    featured: false,
  },
  {
    title: "AeroSprint Ultralight Running Lumbar Pack",
    category: "Bags & Travel",
    brand: "Field Notes",
    description: "Zero-bounce breathable ripstop waist pack with headphone port, key clip, and expandable storage for smartphone and energy gels.",
    basePrice: 1299,
    baseDiscountPrice: 949,
    stock: 70,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=900&q=80", publicId: "prod/waistpack-1", isPrimary: true }],
    ratingsAverage: 4.5,
    ratingsQuantity: 120,
    tags: ["bags", "waistpack", "running", "sports"],
    featured: false,
  },
  {
    title: "Orbit Tech Dopp Kit & Cable Organizer",
    category: "Bags & Travel",
    brand: "Field Notes",
    description: "Origami-style accordion opening with elastic cable loops, SD card slots, power bank pocket, and water-resistant Cordura exterior.",
    basePrice: 1899,
    baseDiscountPrice: 1399,
    stock: 55,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=900&q=80", publicId: "prod/dopp-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 340,
    tags: ["bags", "organizer", "tech", "edc"],
    featured: false,
  },
  {
    title: "Haven Heavyweight Organic Canvas Zip Tote 18L",
    category: "Bags & Travel",
    brand: "Field Notes",
    description: "16oz washed organic cotton canvas utility tote featuring a secure zippered top closure, water bottle holder, and reinforced dual handles.",
    basePrice: 1999,
    baseDiscountPrice: 1499,
    stock: 48,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=900&q=80", publicId: "prod/tote-1", isPrimary: true }],
    ratingsAverage: 4.6,
    ratingsQuantity: 180,
    tags: ["bags", "tote", "canvas", "everyday"],
    featured: false,
  },
  {
    title: "Crossbody Tech Sling Pack 5L",
    category: "Bags & Travel",
    brand: "Field Notes",
    description: "Minimalist everyday sling with Fidlock magnetic buckle, waterproof YKK Aquaguard zippers, and padded tablet compartment.",
    basePrice: 2499,
    baseDiscountPrice: 1899,
    stock: 45,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=900&q=80", publicId: "prod/sling-1", isPrimary: true }],
    ratingsAverage: 4.7,
    ratingsQuantity: 190,
    tags: ["bags", "sling", "everyday", "sale"],
    featured: false,
  },
  {
    title: "AeroRoll 28L Sealed Roll-Top Backpack",
    category: "Bags & Travel",
    brand: "Field Notes",
    description: "Welded TPU waterproof seams with magnetic rolltop closure, ventilated back panel, reflective night accents, and laptop sleeve.",
    basePrice: 4599,
    baseDiscountPrice: 3599,
    stock: 32,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=900&q=80", publicId: "prod/rolltop-1", isPrimary: true }],
    ratingsAverage: 4.7,
    ratingsQuantity: 145,
    tags: ["bags", "backpack", "cycling", "waterproof"],
    featured: false,
  },
  {
    title: "Commuter Waterproof Tech Backpack 24L",
    category: "Bags & Travel",
    brand: "Field Notes",
    description: "Weatherproof recycled polyester backpack with padded 16-inch laptop pocket, concealed passport security pocket, and luggage pass-through strap.",
    basePrice: 4999,
    baseDiscountPrice: 3899,
    stock: 35,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80", publicId: "prod/backpack-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 275,
    tags: ["bags", "backpack", "travel", "deals", "bestseller"],
    featured: true,
  },
  {
    title: "Vanguard 15-inch Waxed Canvas Messenger Briefcase",
    category: "Bags & Travel",
    brand: "Field Notes",
    description: "Classic heritage courier briefcase with brass hardware, thick bridle leather trim, quick-access trolley strap, and padded fleece laptop compartment.",
    basePrice: 5499,
    baseDiscountPrice: 4299,
    stock: 26,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=900&q=80", publicId: "prod/messenger-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 165,
    tags: ["bags", "messenger", "work", "briefcase", "deals"],
    featured: false,
  },
  {
    title: "Heritage Waxed Canvas Duffle Bag 45L",
    category: "Bags & Travel",
    brand: "Field Notes",
    description: "Rugged weekend duffle bag made from 18oz water-resistant waxed canvas with full-grain leather carry handles and removable shoulder strap.",
    basePrice: 5999,
    baseDiscountPrice: 4699,
    stock: 22,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1547949003-9792a18a2601?auto=format&fit=crop&w=900&q=80", publicId: "prod/duffle-1", isPrimary: true }],
    ratingsAverage: 4.9,
    ratingsQuantity: 130,
    tags: ["bags", "duffle", "travel", "featured"],
    featured: true,
  },
  {
    title: "Nomad Pro Polycarbonate Carry-On Spinner Suitcase",
    category: "Bags & Travel",
    brand: "Field Notes",
    description: "German Makrolon polycarbonate hard shell with TSA-approved combination lock, silent 360-degree Japanese Hinomoto dual wheels, and compression divider.",
    basePrice: 8999,
    baseDiscountPrice: 6999,
    stock: 24,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?auto=format&fit=crop&w=900&q=80", publicId: "prod/luggage-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 215,
    tags: ["bags", "luggage", "travel", "bestseller"],
    featured: true,
  },
  {
    title: "Tactical All-Weather Camera Backpack 32L",
    category: "Bags & Travel",
    brand: "Field Notes",
    description: "Modular padded dividers for 2 DSLR bodies and 5 lenses, quick side access door, tripod mounting straps, and integrated waterproof rainfly.",
    basePrice: 9299,
    baseDiscountPrice: 7499,
    stock: 16,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80", publicId: "prod/cambackpack-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 88,
    tags: ["bags", "camera", "photography", "backpack"],
    featured: false,
  },
  {
    title: "Grand Tour Italian Leather Duffle Bag 38L",
    category: "Bags & Travel",
    brand: "Field Notes",
    description: "Full-grain vacchetta leather cabin bag with reinforced base studs, separate shoe compartment, and padded shoulder strap.",
    basePrice: 11999,
    baseDiscountPrice: 9499,
    stock: 18,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80", publicId: "prod/bag-leather-1", isPrimary: true }],
    ratingsAverage: 4.9,
    ratingsQuantity: 98,
    tags: ["bags", "leather", "duffle", "travel", "luxury"],
    featured: true,
  },
  {
    title: "Aluminum Framed 28-Inch Checked Luggage Trunk",
    category: "Bags & Travel",
    brand: "Field Notes",
    description: "Heavy-duty aerospace aluminum frame luggage with dual recessed TSA butterfly latch locks, impact-proof corner guards, and 90L capacity.",
    basePrice: 21999,
    baseDiscountPrice: 16999,
    stock: 10,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?auto=format&fit=crop&w=900&q=80", publicId: "prod/alumluggage-1", isPrimary: true }],
    ratingsAverage: 4.9,
    ratingsQuantity: 42,
    tags: ["bags", "luggage", "travel", "luxury"],
    featured: true,
  },

  // =========================================================================
  // 7. HOME & LIVING (15 Products: <1k, 1k-3k, 3k-8k, >8k)
  // =========================================================================
  {
    title: "Handcrafted Acacia Wood Coasters (Set of 4)",
    category: "Home & Living",
    brand: "Hearth & Co",
    description: "Solid sustainably harvested acacia hardwood drink coasters with laser-etched geometric grooves and non-scratch felt base pads.",
    basePrice: 799,
    baseDiscountPrice: 599,
    stock: 90,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1593062096033-9a26b09da705?auto=format&fit=crop&w=900&q=80", publicId: "prod/coasters-1", isPrimary: true }],
    ratingsAverage: 4.7,
    ratingsQuantity: 280,
    tags: ["home", "wood", "dining", "deals"],
    featured: false,
  },
  {
    title: "Stoneware Ceramic Incense Burner Bowl",
    category: "Home & Living",
    brand: "Hearth & Co",
    description: "Hand-thrown speckled stoneware ceramic incense holder filled with natural white sand for stick, cone, and spiral incense burning.",
    basePrice: 899,
    baseDiscountPrice: 699,
    stock: 75,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=900&q=80", publicId: "prod/incense-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 190,
    tags: ["home", "incense", "decor", "sale"],
    featured: false,
  },
  {
    title: "Stainless Steel Japanese Cocktail Jigger & Spoon",
    category: "Home & Living",
    brand: "Hearth & Co",
    description: "Mirror-polished 18/8 stainless steel double-sided measuring jigger (30ml/60ml) with spiral bar mixing spoon.",
    basePrice: 849,
    baseDiscountPrice: 649,
    stock: 80,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=900&q=80", publicId: "prod/jigger-1", isPrimary: true }],
    ratingsAverage: 4.6,
    ratingsQuantity: 130,
    tags: ["home", "barware", "kitchen"],
    featured: false,
  },
  {
    title: "Botanica Hand-Poured Amber Soy Candle Trio",
    category: "Home & Living",
    brand: "Hearth & Co",
    description: "Trio of 100% natural soy wax candles infused with essential oils of Cedarwood, Amber Noir, and Japanese Yuzu with crackling wooden wicks.",
    basePrice: 1799,
    baseDiscountPrice: 1299,
    stock: 60,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=900&q=80", publicId: "prod/candles-1", isPrimary: true }],
    ratingsAverage: 4.7,
    ratingsQuantity: 280,
    tags: ["home", "candles", "aroma", "deals"],
    featured: false,
  },
  {
    title: "AeroGlass Insulated Thermal Mugs 350ml (Set of 4)",
    category: "Home & Living",
    brand: "Hearth & Co",
    description: "Hand-blown double wall insulated glasses that keep espresso, latte, or tea piping hot while remaining cool to the touch.",
    basePrice: 1699,
    baseDiscountPrice: 1249,
    stock: 50,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=900&q=80", publicId: "prod/mugs-1", isPrimary: true }],
    ratingsAverage: 4.7,
    ratingsQuantity: 340,
    tags: ["home", "coffee", "kitchen", "deals"],
    featured: false,
  },
  {
    title: "Kuro Ceramic Ramen & Donburi Bowls (Set of 2)",
    category: "Home & Living",
    brand: "Hearth & Co",
    description: "Matte black reactive glaze stoneware bowls with matching bamboo chopsticks, soup spoons, and notched rests.",
    basePrice: 1999,
    baseDiscountPrice: 1499,
    stock: 35,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=900&q=80", publicId: "prod/bowls-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 195,
    tags: ["home", "kitchen", "dining", "stoneware"],
    featured: false,
  },
  {
    title: "Zenith Merino Wool Felt & Natural Cork Desk Mat",
    category: "Home & Living",
    brand: "Hearth & Co",
    description: "90x40cm premium desk pad crafted with 100% natural Merino wool felt on high-density anti-slip natural Portuguese cork base.",
    basePrice: 2199,
    baseDiscountPrice: 1699,
    stock: 45,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80", publicId: "prod/deskmat-1", isPrimary: true }],
    ratingsAverage: 4.9,
    ratingsQuantity: 410,
    tags: ["home", "desk", "workspace", "bestseller"],
    featured: true,
  },
  {
    title: "Artisan Solid Walnut Magnetic Kitchen Knife Bar",
    category: "Home & Living",
    brand: "Hearth & Co",
    description: "Powerful hidden neodymium rare-earth magnets embedded in sustainably harvested solid American walnut with flush wall mounting.",
    basePrice: 2299,
    baseDiscountPrice: 1699,
    stock: 30,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1593618998160-e34014e67546?auto=format&fit=crop&w=900&q=80", publicId: "prod/knifestrip-1", isPrimary: true }],
    ratingsAverage: 4.9,
    ratingsQuantity: 210,
    tags: ["home", "kitchen", "walnut", "organization"],
    featured: false,
  },
  {
    title: "Nordic Minimalist Ceramic Pour-Over Coffee Set",
    category: "Home & Living",
    brand: "Hearth & Co",
    description: "Hand-thrown matte ceramic dripper with heat-resistant borosilicate glass carafe and reusable stainless steel micro-mesh filter.",
    basePrice: 2299,
    baseDiscountPrice: 1799,
    stock: 35,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=900&q=80", publicId: "prod/coffee-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 240,
    tags: ["home", "coffee", "kitchen", "bestseller"],
    featured: true,
  },
  {
    title: "Aegean Plush Waffle Bath Towels Set of 2",
    category: "Home & Living",
    brand: "Hearth & Co",
    description: "Ultra-absorbent 600 GSM long-staple Turkish organic cotton bath towels featuring deep waffle honeycomb texture for rapid drying.",
    basePrice: 2499,
    baseDiscountPrice: 1899,
    stock: 40,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=900&q=80", publicId: "prod/towels-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 155,
    tags: ["home", "bath", "towels", "organic"],
    featured: false,
  },
  {
    title: "Aura Ultrasonic Ceramic Aroma Diffuser",
    category: "Home & Living",
    brand: "Hearth & Co",
    description: "Handcrafted stone ceramic ultrasonic aromatherapy diffuser with ambient warm LED nightlight and whisper-quiet ultrasonic atomization.",
    basePrice: 3499,
    baseDiscountPrice: 2699,
    stock: 40,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=900&q=80", publicId: "prod/diffuser-1", isPrimary: true }],
    ratingsAverage: 4.7,
    ratingsQuantity: 310,
    tags: ["home", "aroma", "decor", "deals"],
    featured: false,
  },
  {
    title: "Solid Walnut Monitor Stand & Desk Organizer",
    category: "Home & Living",
    brand: "Hearth & Co",
    description: "Handcrafted solid American walnut wood desk shelf with integrated cork padding, keyboard stow space, and aluminum cable management channel.",
    basePrice: 4299,
    baseDiscountPrice: 3499,
    stock: 28,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1593062096033-9a26b09da705?auto=format&fit=crop&w=900&q=80", publicId: "prod/deskshelf-1", isPrimary: true }],
    ratingsAverage: 4.9,
    ratingsQuantity: 175,
    tags: ["home", "desk", "organization", "bestseller"],
    featured: true,
  },
  {
    title: "Lumière Minimalist Brass & Marble LED Glow Lamp",
    category: "Home & Living",
    brand: "Hearth & Co",
    description: "Brushed brass arch lamp anchored by a solid white Carrara marble base with touch stepless dimming and warm 2700K ambient light.",
    basePrice: 4899,
    baseDiscountPrice: 3899,
    stock: 22,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80", publicId: "prod/lamp-1", isPrimary: true }],
    ratingsAverage: 4.8,
    ratingsQuantity: 130,
    tags: ["home", "lighting", "decor", "luxury"],
    featured: true,
  },
  {
    title: "Pre-Seasoned Heavy Cast Iron Dutch Oven 5.5 Qt",
    category: "Home & Living",
    brand: "Hearth & Co",
    description: "Enameled heavy cast iron casserole pot with stainless steel lid knob, self-basting spikes, and superior thermal retention.",
    basePrice: 5799,
    baseDiscountPrice: 4499,
    stock: 18,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=900&q=80", publicId: "prod/dutchoven-1", isPrimary: true }],
    ratingsAverage: 4.9,
    ratingsQuantity: 110,
    tags: ["home", "kitchen", "cookware", "castiron"],
    featured: false,
  },
  {
    title: "Ergonomic Full-Grain Leather & Aluminum Desk Chair",
    category: "Home & Living",
    brand: "Hearth & Co",
    description: "Executive mid-century modern task chair crafted from top-grain Italian leather with polished aluminum five-star base and pneumatic height adjustment.",
    basePrice: 23999,
    baseDiscountPrice: 18999,
    stock: 10,
    hasVariants: false,
    images: [{ url: "https://images.unsplash.com/photo-1593062096033-9a26b09da705?auto=format&fit=crop&w=900&q=80", publicId: "prod/chair-1", isPrimary: true }],
    ratingsAverage: 4.9,
    ratingsQuantity: 58,
    tags: ["home", "furniture", "desk", "luxury"],
    featured: true,
  },
];

const slugify = (value) =>
  value
    .toLowerCase()
    .trim()
    .replace(/[^\w\s-]/g, "")
    .replace(/[\s_-]+/g, "-")
    .replace(/^-+|-+$/g, "");

async function seedCategories() {
  const categoryMap = new Map();

  for (const cat of categoriesData) {
    const slug = slugify(cat.name);
    const categoryDoc = await Category.findOneAndUpdate(
      { slug },
      {
        $set: {
          name: cat.name,
          slug,
          description: cat.description,
          isActive: true,
        },
      },
      { upsert: true, returnDocument: "after", runValidators: true }
    );
    categoryMap.set(cat.name, categoryDoc._id);
  }

  // Remove any legacy categories not in the active catalog list
  const validCategorySlugs = categoriesData.map((c) => slugify(c.name));
  await Category.deleteMany({ slug: { $nin: validCategorySlugs } });

  console.log(`✓ Seeded ${categoryMap.size} product categories.`);
  return categoryMap;
}

export async function seedProducts({ isStandalone = false, force = true } = {}) {
  if (!process.env.MONGO_URI && mongoose.connection.readyState === 0) {
    throw new Error("MONGO_URI environment variable is missing.");
  }

  console.log("=== STARTING 105-PRODUCT CATALOG SEEDING (15 PER CATEGORY) ===");
  if (mongoose.connection.readyState === 0) {
    await mongoose.connect(process.env.MONGO_URI);
  }

  const categoryMap = await seedCategories();

  // Clear existing products to ensure clean catalog with full fields if force=true
  if (force) {
    const deleteResult = await Product.deleteMany({});
    console.log(`✓ Cleared ${deleteResult.deletedCount} previous products.`);
  }

  const productsToInsert = productsData.map((p) => {
    const slug = slugify(p.title);
    const categoryId = categoryMap.get(p.category);

    if (!categoryId) {
      throw new Error(`Category not found for product: ${p.title} (category: ${p.category})`);
    }

    return {
      title: p.title,
      slug,
      description: p.description,
      brand: p.brand,
      category: categoryId,
      images: p.images,
      basePrice: p.basePrice,
      baseDiscountPrice: p.baseDiscountPrice,
      stock: p.stock,
      hasVariants: p.hasVariants || false,
      variants: p.variants || [],
      ratingsAverage: p.ratingsAverage,
      ratingsQuantity: p.ratingsQuantity,
      tags: p.tags || [],
      isPublished: true,
      featured: p.featured || false,
    };
  });

  const inserted = await Product.insertMany(productsToInsert);
  console.log(`🎉 SUCCESS: Seeded ${inserted.length} rich products directly into Database!`);

  // Print summary by category
  const counts = await Product.aggregate([
    {
      $group: {
        _id: "$category",
        count: { $sum: 1 },
      },
    },
  ]);

  console.log("=== PRODUCT DISTRIBUTION ===");
  for (const c of counts) {
    const cat = await Category.findById(c._id);
    console.log(`- ${cat?.name || "Other"}: ${c.count} products`);
  }

  if (isStandalone) {
    await mongoose.disconnect();
    console.log("✓ MongoDB Disconnected");
  }

  return { categoriesCount: categoryMap.size, productsCount: inserted.length };
}

export async function autoSeedIfEmpty() {
  try {
    const productCount = await Product.countDocuments();
    if (productCount === 0) {
      console.log("⚡ Database is empty on startup. Auto-seeding 105 catalog products...");
      await seedProducts({ isStandalone: false, force: false });
    } else {
      console.log(`✓ Live database has ${productCount} products.`);
    }
  } catch (err) {
    console.error("⚠️ Auto-seed check warning:", err.message);
  }
}

// Auto-run if executed directly as a node script
if (process.argv[1] && process.argv[1].replace(/\\/g, "/").endsWith("seedProducts.js")) {
  seedProducts({ isStandalone: true, force: true })
    .catch((err) => {
      console.error("❌ Seed failed:", err);
      process.exitCode = 1;
    });
}
